"""empty message

Revision ID: 942f021f8dcf
Revises: 
Create Date: 2018-03-02 14:18:16.324874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942f021f8dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('user_password', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('article_title', sa.String(length=50), nullable=True),
    sa.Column('article_content', sa.String(length=50), nullable=True),
    sa.Column('article_date', sa.Date(), nullable=True),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.String(length=50), nullable=True),
    sa.Column('comment_date', sa.Date(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('articleid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['articleid'], ['article.article_id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article')
    op.drop_table('user')
    # ### end Alembic commands ###
